language: python
python:
  - 3.6

  matrix:
    - TEST_DIR=tests/

# Setup anaconda
before_install:
# Install packages
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

# command to install dependencies
install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      conda install --quiet --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib cython ipython h5py vtk;
    else
      conda install --quiet --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib cython ipython h5py;
    fi
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests

script:
  - nosetests $TEST_DIR --with-cov --cov SimPEG --cov-config .coveragerc -v -s

notifications:
  email:
    - skang@eoas.ubc.ca
