language: python
python:
- 3.6
- "nightly"
matrix:
  allow_failures:
    - python: "nightly"

sudo: false

env:
  - TEST_DIR=tests

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/anaconda/bin:$HOME/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda env create -f environment.yml
  - source activate simpegEM1D-environment
  - export MPLBACKEND="agg"
  - pip install -r requirements_dev.txt
  - python setup.py install

script:
  - travis_wait 20 nosetests $TEST_DIR -v -s

after_success: coveralls
