name: simpegEM1D-environment

addons:
  apt_packages:
    - gfortran

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - mkl
  - pip:
    - pymatsolver
    - git+https://github.com/simpeg/simpegEM1D.git@speed_up_leon
