name: simpegEM1D-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - mkl
  - pip:
    - pymatsolver
    - git+https://github.com/sgkang/empymod.git@simpegEM1D
    - git+https://github.com/simpeg/simpegEM1D.git@master
