name: simpegem1d-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - mkl
  - pip:
    - empymod
    - pymatsolver
    - multiprocess
    - SimPEG
    - discretize
    - git+https://github.com/simpeg/simpegEM1D.git@test_travis
